# Rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
  source ~/.config/nvim/plugins/rust.rc.vim
'''

# HTML&CSS
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','css','javascript','jsx','tsx','javascriptreact','typescriptreact']

# TypeScript
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript','tsx']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescript','tsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['typescript','tsx']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['typescript','tsx']
